apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer-service
  name: consumer-service
spec:
  type: NodePort
  ports:
  - name: consumer-port
    port: 8081
    nodePort: 30161
    targetPort: 8081
  selector:
    app: consumer
