apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: docker.io/8884654123/consumer_gcloud1:latest
        imagePullPolicy: IfNotPresent
        name: consumer
        ports:
        - containerPort: 8081
