apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer-service
  name: producer-service
spec:
  type: NodePort
  ports:
  - name: producer-port
    port: 8080
    nodePort: 30151
    targetPort: 8080
  selector:
    app: producer
